### ISSUE TITLE
Create Registration Forms

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#3]
We need forms for:

Projects -- [last year's form here](https://docs.google.com/forms/d/1D56H_1m6IYHQp_yhF4dWM73efN5uhB2ZWqu_6A5X0K4/edit?usp=sharing).
Sites --[last year's form here](https://docs.google.com/forms/d/1RzybCA9Mf1s5_KMTBdgPQHq4XvlWF-yBZvGnaqTazyY/edit?usp=sharing)

- [x] Create forms (copy from last year) - @acabunoc
  - [x] Site Registration - https://goo.gl/forms/O69KyqXoVcujQRdA3
  - [x] Project Registration - https://goo.gl/forms/uaGE7CT3vVXHcaWJ2
       - both forms are in [this folder](https://drive.google.com/drive/folders/1FKC2wtL3oFO5fbD8-rCqotaH8v_lx9NE) -- please feel free to move this folder where it should be!
- [x] Edit the form with questions for this year - @zee-moz (with input from @Lottarao & @KevZawacki)
- [x] Add email confirmation to site hosts when they fill out the form @acabunoc
  - [x] Write email content @zee-moz (can add it in a comment below)
- [x] Add email confirmation to project leads when they fill out the form @acabunoc
  - [x] Write [email content](https://docs.google.com/document/d/1D_JY_GSm0yI8JGc86P7AT35LHoBgYKSXciU9JSKhWpU/edit?usp=sharing) @acabunoc
  - [x] Write [template for GitHub issue](https://github.com/mozilla/2018-global-sprint-planning/issues/3#issuecomment-362662115) listing project (copy again) @acabunoc
- [x] Get GitHub repo ready for new projects - @acabunoc
  - [x] Label & milestone projects from 2017 - @acabunoc
  - [x] close projects from 2017 - @acabunoc

Project form generates GitHub issue in GS Repo. @acabunoc to work on this project.

**Let's add a couple new questions to better capture the story behind each project/site, and each lead's/host's motivation. Suggestions: ** 

**Projects**
What's the most unique or exciting aspect of this project? 
What impact or change will this project create?
What motivated you to create or join this project? 

**Sites**
What's unique or special about your site? 
Who do you hope will join you at your site?

**Comment by zee-moz** [comment]
@lottarao feel free to comment on new questions here! @kevZawacki as well.

**Comment by abbycabs** [comment]
Task breakdown with person responsible (as far as I can tell)
(moved to top comment!)

**Comment by abbycabs** [comment]
@zee-moz I'll wait till you've finalized questions before implementing the email script. This way it won't accidentally break if questions are changed!

**Comment by zee-moz** [comment]
@acabunoc I think we can go with this set of questions. @Lottarao @KevZawacki  any thoughts or input before we go ahead?

**Comment by abbycabs** [comment]
@zee-moz just so you know they're both exactly the same as last year. Happy to go forward with this set of questions.
  - Site Registration - https://goo.gl/forms/O69KyqXoVcujQRdA3
  - Project Registration - https://goo.gl/forms/uaGE7CT3vVXHcaWJ2

**Comment by abbycabs** [comment]
Project registration [email content](https://docs.google.com/document/d/1D_JY_GSm0yI8JGc86P7AT35LHoBgYKSXciU9JSKhWpU/edit?usp=sharing) - please remix!

**Comment by KevZawacki** [comment]
@zee-moz Questions work for me! 👍 Looking forward to reading the responses.

**Comment by abbycabs** [comment]
Issue template. Let me know if you want any changes.

***

**[ Project Contact ]** <%= facilitator %> 
**[ GitHub Repo ]** <%= link %>
**[ Track ]** <%= track %>
**[ Location ]** <%= location %>

### Description
<%= description %>
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, <%= facilitator %>! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [ ] Provide a GitHub repository for work and discussion on your project in a comment
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [ ] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task. 
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] [Fill out this form](https://www.mozillapulse.org/add) to submit your project to Mozilla Pulse. Add the tags `mozsprint` and `2018`.

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready to be featured on Mozilla Pulse`. Your wrangler will review this issue and approve your project if everything looks good :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/). We're here to help you through this process.

**Comment by zee-moz** [comment]
@acabunoc can we add the questions that I put in the original issue, up top? 3 for projects, 2 for sites. Thanks!  😸

**Comment by abbycabs** [comment]
@zee-moz done! you should have edit access to the forms -- let me know if there's a problem. I know there are links and copy from last year's sprint in the forms -- please make sure you're okay with that!

I moved the checklist to the top comment. Once you (@zee-moz) send me copy for the site host confirmation & are good with the copy for project confirmation & issue template, I'll go ahead and setup email integration.

**Comment by zee-moz** [comment]
A couple of questions about the form @stephwright @Saallen @acabunoc  -- we have a list of communities on last year's registration forms-- listing Mozilla Science, the Hives, Women in Tech, Mozilla Clubs, etc... Should we keep this list with historical programs that we no longer support? How should we edit it?  Or should we just keep our internet health issues as main points of entry, and not ask about communities?

**Comment by Saallen** [comment]
I dont think we should keep this historical list as the community dont identify themselves under these titles any more- I would advise to just list issues

**Comment by zee-moz** [comment]
@Saallen thanks! Will do.

**Comment by zee-moz** [comment]
@acabunoc 

- I updated the Registration forms-- maybe take one final look yourself, otherwise they are good to go. I added confirmation messages-- let me know if the one for project form is OK.
- I'm listing globalsprint@mozillafoundation.org as the email for questions-- sound OK
- I updated both the file names and the links listed in the reg forms for the "how-to" info. We are making the GH pages a training site so the reference pages are now: https://mozilla.github.io/global-sprint/project-lead-guide/ and https://mozilla.github.io/global-sprint/site-hosts-guide/. the site looks a bit wonky as a result of the file name changes but I'll work on it Tuesday-- we may do a full overhaul to convert it to a training site, as most info is now on the Foundation pages.
- [Site host email is here](https://docs.google.com/document/d/1vEl5p_nTI0GcqkGviVuFUGEPubD17rZnmjeKWUT68xM/edit)
- I added an explanation of what a "wrangler" is in the PL email, as it's mentioned in the template but not explained
- I'd like the link to the GItHub repo listed at top of the template to be link to README in GH repo-- this is way friendlier for newbies than seeing the code/content files in repo when the click thru

I  think that's it!

**Comment by abbycabs** [comment]
Everything sounds good except the last point on linking directly to the README which bring up a few options:

1. we could add a separate question asking for a link to their README in the registration form
2. we could try to guess what their README link is (probably /README.md). If we guess wrong the link will break (sometimes readmes are just README (no filetype), README.txt, README.Rmd, etc
3. we could use the GitHub api to figure out what github thinks the README is and link to that, then link to the base repo if there is none.

For 1), this might be tricky for people new to github to figure out how to link to this. 2) would work in *most* cases if we guess /README.md, but it would break at least a few times. 3) is the cleanest solution but I'm pretty short on time right now.

I thought you were talking about Pulse projects when you asked about linking to a README before!

I'm going to go ahead and implement everything without this for now. Eager to hear your thoughts on which direction to go!

**Comment by abbycabs** [comment]
I'll close all the 2017 issues once we launch the new site so I can programmatically comment on each issue as it's closed with something like:

> Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? Our [Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/) is open!

**Comment by abbycabs** [comment]
Emails are up and working for when projects fill out the form! [google script used](https://github.com/mozilla/global-sprint/blob/master/scripts/google_form.js) and [issue template used](https://github.com/mozilla/global-sprint/blob/master/issue-template.md). Let me know if we need to change any of the links in the issue template! I'll have to update the script again.

I'll add the automated email for site hosts once I have access to [the content](https://docs.google.com/document/d/1vEl5p_nTI0GcqkGviVuFUGEPubD17rZnmjeKWUT68xM/edit)

**Comment by abbycabs** [comment]
This is good to go! Closing :) @zee-moz, let me know if I forgot anything
