### ISSUE TITLE
Create communication plan

### ISSUE THREAD

**Issue by zee-moz** [mozilla/2018-global-sprint-planning#7]
From meeting with Kevin @kevZawacki & Lotta @lottarao

**Insights**
- press are most interested in individual projects
- if they are remote or in a unique local, sites could make an interesting story
- what is the motivation of the project lead/site host?
- look for stories that are bigger than sprint
- can this serve more explicitly as a kick-off event around IH learning?
- fellows involvement-- splice together video of fellows talks?

**Foundation comms priorities:**
- OKR for more fellows press
- stress the global aspect of the sprint

**To-Dos** 
- [x] Kevin to create comms plan -- draft before Feb 12th launch(?)
- [x] edit project & site form to look for stories (work with ACM) see #3 
- [x] review and create a list of project and individuals involved for lotta and kevin to work with (this for mid-march)
- [x] create survey see #4

**Comment by zee-moz** [comment]
Communication Plan is here! https://docs.google.com/document/d/1vuT1oR_xTQYRBewYbjKpfygnDUXl352BXZ2wrZhaeII/edit?ts=5a788da1#
